### ISSUE TITLE
Refactoring of Postgres queries from normalized to denormalized

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-DSL#11]
AS AN Architect
I WANT all of Bürokratt's current Postgres queries to be refactored as denormalized database queries
SO THAT they would all be consistent with Bürokratt's architectural requirements to database queries

### Acceptance Criteria

- [ ] All requests to currently existing Ruuter endpoints must remain intact by default
- [ ] Only `INSERT` and `SELECT` queries can be used
- [ ] `UPDATE`, `DELETE`, and `JOIN`, but not limited to, can not be used
- [ ] Every intent has to be a separate entry in its respective database table
- [ ] Existing database queries are structured in a way that they will meet the concept of [RESTful naming convention](https://restfulapi.net/resource-naming)

#### Scope

- [ ] _TO BE - https://github.com/buerokratt/Buerokratt-DSL/tree/main/Resql_
- [ ] AS IS - https://github.com/buerokratt/Buerokratt-DSL/tree/alpha-2.0/Resql
- [ ] Requests to Resql initiated within Ruuter DSLs are subject to change if necessary
- [ ] New database queries are created where relevant
- [ ] Existing database queries are removed where relevant
