### ISSUE TITLE
Automated pipelines to archive excess data

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-DSL#13]
AS AN Architect
I WANT to have automated pipelines to archive excess data
SO THAT in case of database breach, only the minimum amount of data could be exposed to leaking

### Acceptance Criteria

- [ ] Uses database queries to list outdated database entries as input
- [ ] Data is transferred to a predefined (external) destination
- [ ] Validate the success of data archiving
- [ ] Delete excess data from source
