### ISSUE TITLE
Automated pipeline to reverse data archiving

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-DSL#14]
> [!IMPORTANT]
> This functionality would be switched off by default and requires special attention if used in production

AS AN Architect
I WANT TO have an automated pipeline to reverse data archiving
SO THAT in case of necessity, data could be transferred from archive to production

### Acceptance Criteria

- [ ] Source database and table are defined
- [ ] Amount of rows to be reverse-archived can be defined
- [ ] A time period to reverse archived data can be defined
- [ ] An event of reverse data archiving is stored in a respective database table
- [ ] An event of reverse data archiving triggers an alert by sending an email to a predefined email
- [ ] Reverse data archived entries are made to destination database table(s) with a respective flag

#### Scope

- [ ] Also part of [NoOps](https://github.com/buerokratt/NoOps)
