### ISSUE TITLE
Turvis rulesets for HTTP requests

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-DSL#15]
AS A SecOps
I WANT Turvis rulesets for HTTP requests to be implemented
SO THAT I could add extra verification layers to incoming requests of my choice

### Acceptance Criteria

- [ ] All relevant existing functionalities of [Turvis](https://github.com/buerokratt/Turvis) are implemented

#### Scope

- [ ] At least 50 rulesets for HTTP requests are created, implemented, and fully functional
- [ ] Created rulesets must cover as wide range of relevant Turvis' current functionality as possible

### References

- https://github.com/buerokratt/Turvis
- https://github.com/orgs/buerokratt/projects/6/views/1
- https://github.com/buerokratt/Turvis/issues/3
- https://github.com/buerokratt/Turvis/issues/14
