### ISSUE TITLE
Researching current databases in scope of future restructuring

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Buerokratt-DSL#60]
AS AN Architect
I WANT TO have a clear overview and understanding of our current databases in use
SO THAT I could make future decisions for refactoring based on it

### Acceptance Criteria

- [ ] ER diagram for current databases
- [ ] Proposed ER diagram for refactored databases
- [ ] Use [Mermaid](https://mermaid.js.org) for diagrams
